services:
- type: web
  name: task-list-api
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: flask run --host 0.0.0.0 --port 80
  envVars:
  - key: FLASK_ENV
    value: production
