"""Added column to connect goal_id to a task

Revision ID: 037bf8604f70
Revises: 09e19ef4dba2
Create Date: 2023-05-04 11:02:55.907965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037bf8604f70'
down_revision = '09e19ef4dba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###
