"""empty message

Revision ID: 048cccd72138
Revises: 0e507a9f9b1c
Create Date: 2023-05-10 13:57:12.791160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048cccd72138'
down_revision = '0e507a9f9b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
