"""Add new column named title to goal table

Revision ID: 07368cace191
Revises: 551153d8f310
Create Date: 2023-05-07 23:56:22.545721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07368cace191'
down_revision = '551153d8f310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
