"""update relationship

Revision ID: 081da68f3291
Revises: 98ea5b39ca72
Create Date: 2023-05-07 20:27:35.543793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081da68f3291'
down_revision = '98ea5b39ca72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
