"""changed id to task_id

Revision ID: 101ccdb3ffd0
Revises: 34b6ef6a0a86
Create Date: 2023-05-14 16:07:40.214718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101ccdb3ffd0'
down_revision = '34b6ef6a0a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('task', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###
