"""Established relationship between Goal and Task

Revision ID: 10aa8da87d4e
Revises: 8e6d3a17a4ba
Create Date: 2023-05-10 13:12:07.440501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10aa8da87d4e'
down_revision = '8e6d3a17a4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
