"""adds column title to Goal

Revision ID: 12cc5d3f1d18
Revises: fc7341ccc08d
Create Date: 2023-05-04 21:19:24.752337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cc5d3f1d18'
down_revision = 'fc7341ccc08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
