"""empty message

Revision ID: 199388af589d
Revises: 42d5e9943c5e
Create Date: 2023-05-06 15:24:47.515678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199388af589d'
down_revision = '42d5e9943c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
