"""empty message

Revision ID: 20d5d8b45f83
Revises: 811fe4e9dcbb
Create Date: 2023-05-07 13:41:30.254405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20d5d8b45f83'
down_revision = '811fe4e9dcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
