"""change task_title to title in Task model

Revision ID: 2260413c2b8e
Revises: 535d6df62a78
Create Date: 2023-05-11 11:56:32.709902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2260413c2b8e'
down_revision = '535d6df62a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'task_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
