"""empty message

Revision ID: 28405e468053
Revises: 895aa5ab74ee
Create Date: 2023-05-10 15:24:55.316424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28405e468053'
down_revision = '895aa5ab74ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
