"""empty message

Revision ID: 29c6c544b7b8
Revises: 1dabb5ea2f8a
Create Date: 2023-05-10 11:30:33.359925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c6c544b7b8'
down_revision = '1dabb5ea2f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
