"""empty message

Revision ID: 2b053e9bfb73
Revises: c7a4f5de7f29
Create Date: 2023-05-03 16:09:22.107096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b053e9bfb73'
down_revision = 'c7a4f5de7f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'task', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='unique')
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
