"""empty message

Revision ID: 31f4d847a239
Revises: c92b51018762
Create Date: 2023-05-06 21:45:44.522415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f4d847a239'
down_revision = 'c92b51018762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###
