"""empty message

Revision ID: 392ad8a94f34
Revises: dedc14af897f
Create Date: 2023-05-07 14:34:49.352687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392ad8a94f34'
down_revision = 'dedc14af897f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
