"""empty message

Revision ID: 3bbf62f87b67
Revises: 82d552b435ed
Create Date: 2023-05-07 09:04:12.180215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbf62f87b67'
down_revision = '82d552b435ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.drop_column('task')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
