"""empty message

Revision ID: 3f7a76355f7c
Revises: 508af33f47e0
Create Date: 2023-05-10 15:46:41.731596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7a76355f7c'
down_revision = '508af33f47e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True, foreign_key='goal.id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
