"""empty message

Revision ID: 3ff48ca6dfea
Revises: c50073d736fc
Create Date: 2023-05-06 16:05:33.016880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff48ca6dfea'
down_revision = 'c50073d736fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
