"""changes model back to original

Revision ID: 414f774e90b2
Revises: 4847d0c7fd01
Create Date: 2023-05-10 18:38:29.002944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414f774e90b2'
down_revision = '4847d0c7fd01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
