"""empty message

Revision ID: 4f4b12f02485
Revises: 3f7a76355f7c
Create Date: 2023-05-11 10:54:45.735124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4b12f02485'
down_revision = '3f7a76355f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    # ### end Alembic commands ###
