"""created initial schema for Goal model

Revision ID: 53997958b64a
Revises: 593a0ad92d41
Create Date: 2023-05-08 14:50:34.585941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53997958b64a'
down_revision = '593a0ad92d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
