"""empty message

Revision ID: 572b7513aac6
Revises: 0f7158bd9337
Create Date: 2023-05-09 17:57:52.996288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572b7513aac6'
down_revision = '0f7158bd9337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
