"""added if statement with to_dict method

Revision ID: 593a0ad92d41
Revises: 4a0d0caf94ac
Create Date: 2023-05-07 17:59:44.273611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593a0ad92d41'
down_revision = '4a0d0caf94ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
