"""Change nullable True of Task model

Revision ID: 5f94e4f367b2
Revises: fc1960d9031c
Create Date: 2023-05-06 23:47:41.629703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f94e4f367b2'
down_revision = 'fc1960d9031c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
