"""Established one to many relationship between Goal and Task models (Goal-one, Task-many).

Revision ID: 607832292931
Revises: 607b21969085
Create Date: 2023-05-11 00:26:01.512794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607832292931'
down_revision = '607b21969085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'goal_id')
    # ### end Alembic commands ###
