"""Started from beginning again

Revision ID: 615353c32c0b
Revises: ea67644817cc
Create Date: 2023-05-17 06:24:59.088577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615353c32c0b'
down_revision = 'ea67644817cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
