"""empty message

Revision ID: 615420deaf8e
Revises: b1c57bb5ebba
Create Date: 2023-05-12 02:07:12.145042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615420deaf8e'
down_revision = 'b1c57bb5ebba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
