"""Added title attribute to Goal model

Revision ID: 629fe8891791
Revises: ef7ef35dc542
Create Date: 2023-05-09 13:38:39.130886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629fe8891791'
down_revision = 'ef7ef35dc542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
