"""empty message

Revision ID: 62a3f83de7cb
Revises: becdf75cfae1
Create Date: 2023-05-03 21:39:03.624863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a3f83de7cb'
down_revision = 'becdf75cfae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
