"""empty message

Revision ID: 676f745d0891
Revises: 3ff48ca6dfea
Create Date: 2023-05-06 18:18:25.234776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676f745d0891'
down_revision = '3ff48ca6dfea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
