"""empty message

Revision ID: 703bddc44bd3
Revises: 9e78bef31d9a
Create Date: 2023-05-08 19:14:58.990697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703bddc44bd3'
down_revision = '9e78bef31d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
