"""empty message

Revision ID: 71effdfc8fea
Revises: 7f4c16571484
Create Date: 2023-05-04 13:12:00.402536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71effdfc8fea'
down_revision = '7f4c16571484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
