"""Add relationship one to many btw goal and task

Revision ID: 730d2268fd36
Revises: 8cc5dc8b941a
Create Date: 2023-05-08 21:20:38.855458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730d2268fd36'
down_revision = '8cc5dc8b941a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
