"""edited task model

Revision ID: 743203a498cc
Revises: fadc228b98e2
Create Date: 2023-05-13 22:26:40.957135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743203a498cc'
down_revision = 'fadc228b98e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
