"""empty message

Revision ID: 752f75d87db9
Revises: dc7d0c82fedf
Create Date: 2023-05-08 13:33:49.457039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752f75d87db9'
down_revision = 'dc7d0c82fedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
