"""empty message

Revision ID: 794ed4940cb9
Revises: 7a9e61f43da2
Create Date: 2023-05-08 08:12:25.133504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794ed4940cb9'
down_revision = '7a9e61f43da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
