"""empty message

Revision ID: 7b2185152ef9
Revises: 71566c90a087
Create Date: 2023-05-12 21:46:34.974742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2185152ef9'
down_revision = '71566c90a087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###
