"""empty message

Revision ID: 811fe4e9dcbb
Revises: 32872ffe494c
Create Date: 2023-05-07 12:58:15.663080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '811fe4e9dcbb'
down_revision = '32872ffe494c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('is_complete', sa.DateTime(), nullable=True))
    op.drop_column('task', 'completed_at')
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('task', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('task', 'is_complete')
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
