"""empty message

Revision ID: 8133a45635b8
Revises: a2cdae4d6dcf
Create Date: 2023-05-06 20:12:55.799255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8133a45635b8'
down_revision = 'a2cdae4d6dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###
