"""empty message

Revision ID: 823b1eeeb0dd
Revises: 9ce7ae4a0038
Create Date: 2023-05-10 11:27:31.039112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823b1eeeb0dd'
down_revision = '9ce7ae4a0038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
