"""implemented one-to-many relationship between Goal and Task models

Revision ID: 85151472ae19
Revises: 1451af6398fb
Create Date: 2023-05-10 12:22:34.719989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85151472ae19'
down_revision = '1451af6398fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
