"""empty message

Revision ID: 884d09999e02
Revises: 6f84a3f58fd3
Create Date: 2023-05-09 15:57:39.270127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884d09999e02'
down_revision = '6f84a3f58fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
