"""empty message

Revision ID: 912c7fe20f0a
Revises: abd15a00e7a4
Create Date: 2023-05-06 15:29:10.232192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912c7fe20f0a'
down_revision = 'abd15a00e7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
