"""empty message

Revision ID: 922ff4e50c0f
Revises: b08b93ce55c3
Create Date: 2023-05-03 23:28:39.709606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922ff4e50c0f'
down_revision = 'b08b93ce55c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
