"""empty message

Revision ID: 929c974c27f0
Revises: 89a5c683fea2
Create Date: 2023-05-09 17:46:03.637220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929c974c27f0'
down_revision = '89a5c683fea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
