"""created goal title column

Revision ID: 948eb8bd4f88
Revises: 5dfcde25911e
Create Date: 2023-05-08 16:13:18.944046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948eb8bd4f88'
down_revision = '5dfcde25911e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
