"""empty message

Revision ID: 982476d6934c
Revises: 7b2185152ef9
Create Date: 2023-05-13 19:33:36.992081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982476d6934c'
down_revision = '7b2185152ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
