"""empty message

Revision ID: a2cdae4d6dcf
Revises: 13c6e4dd5868
Create Date: 2023-05-06 20:03:44.422452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cdae4d6dcf'
down_revision = '13c6e4dd5868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###
