"""added read_one_task route

Revision ID: a37985866f46
Revises: 1f58e4a53c1b
Create Date: 2023-05-10 10:48:24.013890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37985866f46'
down_revision = '1f58e4a53c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_title', sa.String(), nullable=True))
    op.drop_column('task', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'task_title')
    # ### end Alembic commands ###
