"""empty message

Revision ID: a7cb21c4476f
Revises: 2b053e9bfb73
Create Date: 2023-05-08 10:05:23.186421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cb21c4476f'
down_revision = '2b053e9bfb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
