"""empty message

Revision ID: c50073d736fc
Revises: 912c7fe20f0a
Create Date: 2023-05-06 15:43:24.488083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50073d736fc'
down_revision = '912c7fe20f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###
