"""empty message

Revision ID: c64140d649de
Revises: ffbc34939026
Create Date: 2023-05-04 15:54:18.115308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c64140d649de'
down_revision = 'ffbc34939026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'completed_date')
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('task', sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    op.drop_column('task', 'id')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
