"""empty message

Revision ID: d40787e04fa4
Revises: f30dbe623280
Create Date: 2023-05-12 04:47:50.516943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40787e04fa4'
down_revision = 'f30dbe623280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goals_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goals_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goals_id')
    # ### end Alembic commands ###
