"""empty message

Revision ID: eb3c213cc824
Revises: a7cb21c4476f
Create Date: 2023-05-08 15:18:25.381541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3c213cc824'
down_revision = 'a7cb21c4476f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.drop_constraint('task_title_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_title_key', 'task', ['title'])
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
